import { FunctionComponent, ReactNode } from 'react'
import { ViewProps } from '@tarojs/components'

/**
 * @title ConfigProvider Props
 */
export interface ConfigProviderProps extends ViewProps {
  /**
   * @description 	自定义主题变量, 具体请查看详情
   */
  themeVars?: IThemeVars
  children: ReactNode
}
/**
 * @forbidToMd true
 */
export type IThemeVars = {
  primaryColor?: string
  actionSheetMaxHeight?: string
  actionSheetHeaderHeight?: string
  actionSheetHeaderFontSize?: string
  actionSheetDescriptionColor?: string
  actionSheetDescriptionFontSize?: string
  actionSheetDescriptionLineHeight?: string
  actionSheetItemBackground?: string
  actionSheetItemFontSize?: string
  actionSheetItemLineHeight?: string
  actionSheetItemTextColor?: string
  actionSheetItemDisabledTextColor?: string
  actionSheetSubnameColor?: string
  actionSheetSubnameFontSize?: string
  actionSheetSubnameLineHeight?: string
  actionSheetCloseIconSize?: string
  actionSheetCloseIconColor?: string
  actionSheetCloseIconPadding?: string
  actionSheetCancelTextColor?: string
  actionSheetCancelPaddingTop?: string
  actionSheetCancelPaddingColor?: string
  buttonLineHeight?: string
  buttonNormalHeight?: string
  buttonNormalFontSize?: string
  buttonNormalBorderRadius?: string
  buttonMiniHeight?: string
  buttonMiniFontSize?: string
  buttonMiniBorderRadius?: string
  buttonMiniMinWidth?: string
  buttonSmallHeight?: string
  buttonSmallFontSize?: string
  buttonSmallBorderRadius?: string
  buttonSmallMinWidth?: string
  buttonLargeHeight?: string
  buttonLargeFontSize?: string
  buttonLargeBorderRadius?: string
  buttonDefaultColor?: string
  buttonDefaultBackgroundColor?: string
  buttonPrimaryColor?: string
  buttonPrimaryBackgroundColor?: string
  buttonInfoColor?: string
  buttonInfoBackgroundColor?: string
  buttonDangerColor?: string
  buttonDangerBackgroundColor?: string
  buttonWarningColor?: string
  buttonWarningBackgroundColor?: string
  buttonBorderWidth?: string
  buttonRoundBorderRadius?: string
  buttonPlainBackgroundColor?: string
  buttonActiveOpacity?: string
  buttonDisabledOpacity?: string
  calendarHeight?: string
  calendarBackgroundColor?: string
  calendarPopupHeight?: string
  calendarHeaderBoxShadow?: string
  calendarHeaderTitleHeight?: string
  calendarHeaderTitleFontSize?: string
  calendarHeaderSubtitleFontSize?: string
  calendarWeekdaysHeight?: string
  calendarWeekdaysFontSize?: string
  calendarMonthTitleFontSize?: string
  calendarMonthMarkColor?: string
  calendarMonthMarkFontSize?: string
  calendarDayHeight?: string
  calendarDayFontSize?: string
  calendarRangeEdgeColor?: string
  calendarRangeEdgeBackgroundColor?: string
  calendarRangeMiddleColor?: string
  calendarRangeMiddleBackgroundOpacity?: string
  calendarSelectedDaySize?: string
  calendarSelectedDayColor?: string
  calendarInfoFontSize?: string
  calendarInfoLineHeight?: string
  calendarSelectedDayBackgroundColor?: string
  calendarDayDisabledColor?: string
  calendarConfirmButtonHeight?: string
  calendarConfirmButtonMargin?: string
  calendarConfirmButtonLineHeight?: string
  cardPadding?: string
  cardFontSize?: string
  cardTextColor?: string
  cardBackgroundColor?: string
  cardThumbSize?: string
  cardTitleLineHeight?: string
  cardDescColor?: string
  cardDescLineHeight?: string
  cardPriceColor?: string
  cardOriginPriceColor?: string
  cardOriginPriceFontSize?: string
  cardPriceFontSize?: string
  cardPriceIntegerFontSize?: string
  cardPriceFontFamily?: string
  cellFontSize?: string
  cellLineHeight?: string
  cellVerticalPadding?: string
  cellHorizontalPadding?: string
  cellTextColor?: string
  cellBackgroundColor?: string
  cellBorderColor?: string
  cellRequiredColor?: string
  cellLabelColor?: string
  cellLabelFontSize?: string
  cellLabelMarginTop?: string
  cellValueColor?: string
  cellIconSize?: string
  cellRightIconColor?: string
  cellLargeVerticalPadding?: string
  cellLargeTitleFontSize?: string
  cellLargeValueFontSize?: string
  cellLargeLabelFontSize?: string
  cellGroupBackgroundColor?: string
  cellGroupTitleColor?: string
  cellGroupTitlePadding?: string
  cellGroupTitleFontSize?: string
  cellGroupTitleLineHeight?: string
  cellGroupInsetPadding?: string
  cellGroupInsetBorderRadius?: string
  cellGroupInsetTitlePadding?: string
  checkboxSize?: string
  checkboxBorderColor?: string
  checkboxTransitionDuration?: string
  checkboxLabelMargin?: string
  checkboxLabelColor?: string
  checkboxCheckedIconColor?: string
  checkboxDisabledIconColor?: string
  checkboxDisabledLabelColor?: string
  checkboxDisabledBackgroundColor?: string
  circleTextColor?: string
  circleFontColor?: string
  collapseItemTransitionDuration?: string
  collapseItemContentPadding?: string
  collapseItemContentFontSize?: string
  collapseItemContentLineHeight?: string
  collapseItemContentTextColor?: string
  collapseItemContentBackgroundColor?: string
  collapseItemTitleDisabledColor?: string
  countDownTextColor?: string
  countDownFontSize?: string
  countDownLineHeight?: string
  dialogWidth?: string
  dialogSmallScreenWidth?: string
  dialogFontSize?: string
  dialogBorderRadius?: string
  dialogBackgroundColor?: string
  dialogHeaderFontWeight?: string
  dialogHeaderLineHeight?: string
  dialogHeaderPaddingTop?: string
  dialogHeaderIsolatedPadding?: string
  dialogMessagePadding?: string
  dialogMessageFontSize?: string
  dialogMessageLineHeight?: string
  dialogMessageMaxHeight?: string
  dialogHasTitleMessageTextColor?: string
  dialogHasTitleMessagePaddingTop?: string
  dialogCancelButtonColor?: string
  dialogConfirmButtonColor?: string
  formBackgroundColor?: string
  formSpaceHorizontal?: string
  formSpaceVertical?: string
  formBorderBottom?: string
  formLineHeight?: string
  formLabelColor?: string
  formLabelWidth?: string
  formLabelFontSize?: string
  formControllMarginLeft?: string
  formControllFontSize?: string
  formMessageFontSize?: string
  formMessageColor?: string
  formMessageMarginTop?: string
  formVerticalControllMarginTop?: string
  fieldLabelColor?: string
  fieldInputTextColor?: string
  fieldInputErrorTextColor?: string
  fieldInputDisabledTextColor?: string
  fieldPlaceholderTextColor?: string
  fieldIconSize?: string
  fieldClearIconSize?: string
  fieldClearIconColor?: string
  fieldIconContainerColor?: string
  fieldErrorMessageColor?: string
  fieldErrorMessageTextFontSize?: string
  fieldWordLimitColor?: string
  fieldWordLimitFontSize?: string
  fieldWordLimitLineHeight?: string
  fieldWordNumFullColor?: string
  fieldDisabledTextColor?: string
  fieldTextAreaMinHeight?: string
  fieldFontSize?: string
  goodsActionBackgroundColor?: string
  goodsActionHeight?: string
  goodsActionIconWidth?: string
  goodsActionIconHeight?: string
  goodsActionIconColor?: string
  goodsActionIconSize?: string
  goodsActionIconFontSize?: string
  goodsActionIconTextColor?: string
  goodsActionButtonHeight?: string
  goodsActionButtonLineHeight?: string
  goodsActionButtonBorderRadius?: string
  goodsActionButtonWarningColor?: string
  goodsActionButtonDangerColor?: string
  goodsActionButtonPlainColor?: string
  imagePlaceholderTextColor?: string
  imagePlaceholderFontSize?: string
  imagePlaceholderBackgroundColor?: string
  imageLoadingIconSize?: string
  imageLoadingIconColor?: string
  imageErrorIconSize?: string
  imageErrorIconColor?: string
  infoSize?: string
  infoColor?: string
  infoPadding?: string
  infoFontSize?: string
  infoFontWeight?: string
  infoBorderWidth?: string
  infoBackgroundColor?: string
  infoDotColor?: string
  infoDotSize?: string
  infoFontFamily?: string
  loadingTextColor?: string
  loadingTextFontSize?: string
  loadingTextLineHeight?: string
  loadingSpinnerColor?: string
  loadingSpinnerSize?: string
  loadingSpinnerAnimationDuration?: string
  navBarHeight?: string
  navBarArrowSize?: string
  navBarTextColor?: string
  navBarTitleFontSize?: string
  navBarTitleTextColor?: string
  noticeBarHeight?: string
  noticeBarPadding?: string
  noticeBarWrapablePadding?: string
  noticeBarFontSize?: string
  noticeBarTextColor?: string
  noticeBarLineHeight?: string
  noticeBarBackgroundColor?: string
  noticeBarIconSize?: string
  noticeBarIconMinWidth?: string
  notifyPadding?: string
  notifyFontSize?: string
  notifyLineHeight?: string
  notifyPrimaryBackgroundColor?: string
  notifySuccessBackgroundColor?: string
  notifyDangerBackgroundColor?: string
  notifyWarningBackgroundColor?: string
  overlayBackgroundColor?: string
  panelBackgroundColor?: string
  panelHeaderValueColor?: string
  panelFooterPadding?: string
  pickerBackgroundColor?: string
  pickerToolbarHeight?: string
  pickerTitleFontSize?: string
  pickerActionPadding?: string
  pickerActionFontSize?: string
  pickerConfirmActionColor?: string
  pickerCancelActionColor?: string
  pickerOptionFontSize?: string
  pickerOptionTextColor?: string
  pickerLoadingIconColor?: string
  pickerLoadingMaskColor?: string
  pickerOptionDisabledOpacity?: string
  pickerOptionSelectedTextColor?: string
  popupBackgroundColor?: string
  popupRoundBorderRadius?: string
  popupCloseIconSize?: string
  popupCloseIconColor?: string
  popupCloseIconMargin?: string
  progressHeight?: string
  progressBackgroundColor?: string
  progressPivotPadding?: string
  progressColor?: string
  progressPivotFontSize?: string
  progressPivotLineHeight?: string
  progressPivotBackgroundColor?: string
  progressPivotTextColor?: string
  radioSize?: string
  radioBorderColor?: string
  radioTransitionDuration?: string
  radioLabelMargin?: string
  radioLabelColor?: string
  radioCheckedIconColor?: string
  radioDisabledIconColor?: string
  radioDisabledLabelColor?: string
  radioDisabledBackgroundColor?: string
  rateHorizontalPadding?: string
  rateIconSize?: string
  rateIconVoidColor?: string
  rateIconFullColor?: string
  rateIconDisabledColor?: string
  rateIconGutter?: string
  switchWidth?: string
  switchHeight?: string
  switchNodeSize?: string
  switchNodeZIndex?: string
  switchNodeBackgroundColor?: string
  switchNodeBoxShadow?: string
  switchBackgroundColor?: string
  switchOnBackgroundColor?: string
  switchTransitionDuration?: string
  switchDisabledOpacity?: string
  switchBorder?: string
  shareSheetHeaderPadding?: string
  shareSheetTitleColor?: string
  shareSheetTitleFontSize?: string
  shareSheetTitleLineHeight?: string
  shareSheetDescriptionColor?: string
  shareSheetDescriptionFontSize?: string
  shareSheetDescriptionLineHeight?: string
  shareSheetIconSize?: string
  shareSheetOptionNameColor?: string
  shareSheetOptionNameFontSize?: string
  shareSheetOptionDescriptionColor?: string
  shareSheetOptionDescriptionFontSize?: string
  shareSheetCancelButtonFontSize?: string
  shareSheetCancelButtonHeight?: string
  shareSheetCancelButtonBackground?: string
  searchBackgroundColor?: string
  searchPadding?: string
  searchInputHeight?: string
  searchLabelPadding?: string
  searchLabelColor?: string
  searchLabelFontSize?: string
  searchLeftIconColor?: string
  searchActionPadding?: string
  searchActionTextColor?: string
  searchActionFontSize?: string
  sidebarWidth?: string
  sidebarFontSize?: string
  sidebarLineHeight?: string
  sidebarTextColor?: string
  sidebarDisabledTextColor?: string
  sidebarPadding?: string
  sidebarActiveColor?: string
  sidebarBackgroundColor?: string
  sidebarSelectedFontWeight?: string
  sidebarSelectedTextColor?: string
  sidebarSelectedBorderColor?: string
  sidebarSelectedBackgroundColor?: string
  sliderActiveBackgroundColor?: string
  sliderInactiveBackgroundColor?: string
  sliderDisabledOpacity?: string
  sliderBarHeight?: string
  sliderButtonWidth?: string
  sliderButtonHeight?: string
  sliderButtonBorderRadius?: string
  sliderButtonBackgroundColor?: string
  sliderButtonBoxShadow?: string
  stepTextColor?: string
  stepProcessTextColor?: string
  stepFontSize?: string
  stepLineColor?: string
  stepFinishLineColor?: string
  stepFinishTextColor?: string
  stepIconSize?: string
  stepCircleSize?: string
  stepCircleColor?: string
  stepHorizontalTitleFontSize?: string
  stepsBackgroundColor?: string
  stepperActiveColor?: string
  stepperBackgroundColor?: string
  stepperButtonIconColor?: string
  stepperButtonDisabledColor?: string
  stepperButtonDisabledIconColor?: string
  stepperButtonRoundThemeColor?: string
  stepperInputWidth?: string
  stepperInputHeight?: string
  stepperInputFontSize?: string
  stepperInputLineHeight?: string
  stepperInputTextColor?: string
  stepperInputDisabledTextColor?: string
  stepperInputDisabledBackgroundColor?: string
  stepperBorderRadius?: string
  submitBarHeight?: string
  submitBarBackgroundColor?: string
  submitBarButtonWidth?: string
  submitBarPriceColor?: string
  submitBarPriceFontSize?: string
  submitBarCurrencyFontSize?: string
  submitBarTextColor?: string
  submitBarTextFontSize?: string
  submitBarTipPadding?: string
  submitBarTipFontSize?: string
  submitBarTipLineHeight?: string
  submitBarTipColor?: string
  submitBarTipBackgroundColor?: string
  submitBarTipIconSize?: string
  submitBarButtonHeight?: string
  submitBarPadding?: string
  submitBarPriceIntegerFontSize?: string
  submitBarPriceFontFamily?: string
  tabbarHeight?: string
  tabbarBackgroundColor?: string
  tabbarItemFontSize?: string
  tabbarItemTextColor?: string
  tabbarItemActiveColor?: string
  tabbarItemLineHeight?: string
  tabbarItemIconSize?: string
  tabbarItemMarginBottom?: string
  tabTextColor?: string
  tabActiveTextColor?: string
  tabDisabledTextColor?: string
  tabFontSize?: string
  tabsDefaultColor?: string
  tabsLineHeight?: string
  tabsCardHeight?: string
  tabsNavBackgroundColor?: string
  tabsBottomBarHeight?: string
  tabsBottomBarColor?: string
  tagPadding?: string
  tagTextColor?: string
  tagFontSize?: string
  tagBorderRadius?: string
  tagLineHeight?: string
  tagMediumPadding?: string
  tagLargePadding?: string
  tagLargeBorderRadius?: string
  tagLargeFontSize?: string
  tagRoundBorderRadius?: string
  tagDangerColor?: string
  tagPrimaryColor?: string
  tagSuccessColor?: string
  tagWarningColor?: string
  tagDefaultColor?: string
  tagPlainBackgroundColor?: string
  toastMaxWidth?: string
  toastFontSize?: string
  toastTextColor?: string
  toastLineHeight?: string
  toastBorderRadius?: string
  toastBackgroundColor?: string
  toastIconSize?: string
  toastTextMinWidth?: string
  toastTextPadding?: string
  toastDefaultPadding?: string
  toastDefaultWidth?: string
  toastDefaultMinHeight?: string
  gridItemContentPadding?: string
  gridItemContentBackgroundColor?: string
  gridItemContentActiveColor?: string
  gridItemIconSize?: string
  gridItemTextColor?: string
  gridItemTextFontSize?: string
  dividerMargin?: string
  dividerTextColor?: string
  dividerFontSize?: string
  dividerLineHeight?: string
  dividerBorderColor?: string
  dividerContentPadding?: string
  dividerContentLeftWidth?: string
  dividerContentRightWidth?: string
  emptyPadding?: string
  emptyImageSize?: string
  emptyDescriptionMarginTop?: string
  emptyDescriptionPadding?: string
  emptyDescriptionColor?: string
  emptyDescriptionFontSize?: string
  emptyDescriptionLineHeight?: string
  emptyBottomMarginTop?: string
  treeSelectFontSize?: string
  treeSelectNavBackgroundColor?: string
  treeSelectContentBackgroundColor?: string
  treeSelectNavItemPadding?: string
  treeSelectItemHeight?: string
  treeSelectItemActiveColor?: string
  treeSelectItemDisabledColor?: string
  uploaderSize?: string
  uploaderIconSize?: string
  uploaderIconColor?: string
  uploaderTextColor?: string
  uploaderTextFontSize?: string
  uploaderUploadBackgroundColor?: string
  uploaderUploadActiveColor?: string
  uploaderDeleteColor?: string
  uploaderDeleteIconSize?: string
  uploaderDeleteBackgroundColor?: string
  uploaderFileBackgroundColor?: string
  uploaderFileIconSize?: string
  uploaderFileIconColor?: string
  uploaderFileNamePadding?: string
  uploaderFileNameMarginTop?: string
  uploaderFileNameFontSize?: string
  uploaderFileNameTextColor?: string
  uploaderMaskBackgroundColor?: string
  uploaderMaskIconSize?: string
  uploaderMaskMessageFontSize?: string
  uploaderMaskMessageLineHeight?: string
  uploaderLoadingIconSize?: string
  uploaderLoadingIconColor?: string
  uploaderDisabledOpacity?: string
  dropdownMenuHeight?: string
  dropdownMenuBackgroundColor?: string
  dropdownMenuTitleFontSize?: string
  dropdownMenuTitleTextColor?: string
  dropdownMenuTitleActiveTextColor?: string
  dropdownMenuTitleDisabledTextColor?: string
  dropdownMenuTitlePadding?: string
  dropdownMenuTitleLineHeight?: string
  dropdownMenuOptionActiveColor?: string
  dropdownMenuBoxShadow?: string
  indexAnchorPadding?: string
  indexAnchorTextColor?: string
  indexAnchorFontWeight?: string
  indexAnchorFontSize?: string
  indexAnchorLineHeight?: string
  indexAnchorBackgroundColor?: string
  indexAnchorActiveBackgroundColor?: string
  indexAnchorActiveTextColor?: string
  indexBarIndexFontSize?: string
  indexBarIndexLineHeight?: string
  indexBarIndexPopupWidth?: string
  indexBarIndexSidebarZindex?: string
  skeletonPadding?: string
  skeletonRowHeight?: string
  skeletonRowBackgroundColor?: string
  skeletonRowMarginTop?: string
  skeletonAvatarBackgroundColor?: string
  skeletonAnimationDuration?: string
  numberKeyboardSignBackgroundColor?: string
  numberKeyboardWeekColor?: string
  tablePrimaryColor?: string
  paginationColor?: string
  paginationFontSize?: string
  paginationItemBorderColor?: string
  paginationActiveBackgroundColor?: string
  paginationDisableColor?: string
  paginationDisableBackgroundColor?: string
  paginationItemBorderWidth?: string
  paginationItemBorderRadius?: string
  paginationPrevNextPadding?: string
  cascaderFontSize?: string
  cascaderLineHeight?: string
  cascaderTabsItemPadding?: string
  cascaderTitlePadding?: string
  cascaderTitleFontSize?: string
  cascaderTitleLineHeight?: string
  cascaderItemPadding?: string
  cascaderItemFontSize?: string
  cascaderItemColor?: string
  cascaderItemActiveColor?: string
  cascaderPaneHeight?: string
  cascaderPanePaddingTop?: string
  cascaderIconChecklistMarginLeft?: string
  swiperPaginationItemBackgroundColor?: string
  ellipsisFontSize?: string
  ellipsisLineHeight?: string
  ellipsisActionFontSize?: string
  ellipsisPrimaryColor?: string
  signatureBorderColor?: string
  signatureBorderWidth?: string
  signatureHeight?: string
  signatureMarginBottom?: string
}

declare const ConfigProvider: FunctionComponent<ConfigProviderProps>

export { ConfigProvider }
