export default {
  pages: [
    'pages/dashboard/index',
    'pages/button/index',
    'pages/cell/index',
    'pages/config-provider/index',
    'pages/icon/index',
    'pages/image/index',
    'pages/col/index',
    'pages/popup/index',
    'pages/common/index',
    'pages/toast/index',
    'pages/transition/index',
    'pages/calendar/index',
    'pages/cascader/index',
    'pages/checkbox/index',
    'pages/datetime-picker/index',
    'pages/field/index',
    'pages/form/index',
    'pages/form-render/index',
    'pages/picker/index',
    'pages/radio/index',
    'pages/rate/index',
    'pages/search/index',
    'pages/slider/index',
    'pages/stepper/index',
    'pages/switch/index',
    'pages/uploader/index',
    'pages/action-sheet/index',
    'pages/dialog/index',
    'pages/dropdown-menu/index',
    'pages/loading/index',
    'pages/notify/index',
    'pages/overlay/index',
    'pages/share-sheet/index',
    'pages/swipe-cell/index',
    'pages/signature/index',
    'pages/table/index',
    'pages/swiper/index',
    'pages/circle/index',
    'pages/collapse/index',
    'pages/count-down/index',
    'pages/divider/index',
    'pages/empty/index',
    'pages/ellipsis/index',
    'pages/notice-bar/index',
    'pages/progress/index',
    'pages/skeleton/index',
    'pages/steps/index',
    'pages/sticky/index',
    'pages/tag/index',
    'pages/water-mark/index',
    'pages/number-keyboard/index',
    'pages/infinite-scroll/index',
    'pages/pull-to-refresh/index',
    'pages/virtual-list/index',
    'pages/waterfall-flow/index',
    'pages/pagination/index',
    'pages/grid/index',
    'pages/index-bar/index',
    'pages/nav-bar/index',
    'pages/sidebar/index',
    'pages/tab/index',
    'pages/tabbar/index',
    'pages/tree-select/index',
    'pages/area/index',
    'pages/sku/index',
    'pages/card/index',
    'pages/submit-bar/index',
    'pages/goods-action/index',
    'pages/result/index',
  ],
  window: {
    navigationBarBackgroundColor: '#f8f8f8',
    navigationBarTitleText: 'antmjs-vantui',
    navigationBarTextStyle: 'black',
    backgroundTextStyle: 'dark',
    backgroundColor: '#f8f8f8',
    titleBarColor: 'black',
  },
  sitemapLocation: 'sitemap.json',
  animation: false,
}
