export declare const CWD: string
export declare const ROOT: string
export declare const ES_DIR: string
export declare const LIB_DIR: string
export declare const VANT_CONFIG_FILE: string
export declare const PACKAGE_JSON_FILE: string
export declare const DEFAULT_DEMO_PAGE_PATH: string
export declare const CJS_DIR: string
export declare const DIST_DIR: string
export declare const CONFIG_DIR: string
export declare const PACKAGE_ENTRY_FILE: string
export declare const PACKAGE_STYLE_FILE: string
export declare const STYLE_DEPS_JSON_FILE: string
export declare const POSTCSS_CONFIG_FILE: string
export declare const SCRIPT_EXTS: string[]
export declare const STYLE_EXTS: string[]
export declare function getPackageJson(): any
export declare function getVantConfig(): any
export declare const SRC_DIR: any
export declare const STYLE_DIR: string
